import type { Metadata } from "next";
import { Geist, Geist_Mono, Jacques_Francois_Shadow, Titillium_Web } from "next/font/google";
import "./globals.css";
import FlyonuiScript from "../components/FlyonuiScript";

const titillium = Titillium_Web({ subsets: ["latin"], weight: ["400", "700"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={titillium.className}>
        <nav className="navbar rounded-box justify-between gap-4 shadow-base-300/20 shadow-sm px-[15%]">
          <div className="navbar-start">
            <a className="link text-base-content link-neutral text-xl font-bold no-underline" href="/">
              Autodomi
            </a>
          </div>

          <div className="navbar-end items-center gap-4">
            <div className="dropdown relative inline-flex [--auto-close:inside] [--offset:9]">
              {/* <button id="dropdown-name" type="button" className="dropdown-toggle btn btn-text btn-circle dropdown-open:bg-base-content/10 dropdown-open:text-base-content" aria-haspopup="menu" aria-expanded="false" aria-label="Dropdown">
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <line x1="3" y1="6" x2="21" y2="6"></line>
          <line x1="3" y1="12" x2="21" y2="12"></line>
          <line x1="3" y1="18" x2="21" y2="18"></line>
        </svg>
      </button> */}
              <ul className="dropdown-menu dropdown-open:opacity-100 hidden" role="menu" aria-orientation="vertical" aria-labelledby="dropdown-name">
                <li><a className="dropdown-item" href="#">Link 1</a></li>
                <li><a className="dropdown-item" href="#">Link 2</a></li>
                <li><a className="dropdown-item" href="#">Link 3</a></li>
                <hr className="border-base-content/25 -mx-2" />
                <li><a className="dropdown-item" href="#">Link 4</a></li>
              </ul>
            </div>
          </div>
        </nav>
        {children}
        <FlyonuiScript />
        <footer className="footer bg-base-200/60 px-[15%] py-4">
          <div className="flex w-full flex-wrap items-center justify-between">
            <div className="flex items-center gap-2 text-xl font-bold text-base-content">

              <span>Autodomi</span>
            </div>
            <aside className="grid-flow-col items-center">
              <p> ©2024 <a className="link link-hover font-medium" href="#">Autodomi</a> </p>
            </aside>
            <div className="flex h-5 gap-4">

              <a href="https://facebook.com" className="link" aria-label="Facebook Link" target="_blank" rel="noopener noreferrer">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
                </svg>
              </a>
              <a href="https://twitter.com" className="link" aria-label="X Link" target="_blank" rel="noopener noreferrer">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24h-6.694l-5.25-6.861-6.004 6.861h-3.307l7.73-8.835L2.376 2.25h6.852l4.978 6.586L17.563 2.25h.681zm-1.097 17.537h1.828L7.031 3.712H5.081l12.066 15.075z" />
                </svg>
              </a>
              <a href="https://google.com" className="link" aria-label="Google Link" target="_blank" rel="noopener noreferrer">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                  <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                  <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                  <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
                </svg>
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
